import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
current_gdp=pd.read_csv("Current_GDP.csv", sep=",", on_bad_lines="skip")
inflation=pd.read_csv("Inflation.csv", sep=",", on_bad_lines="skip")
unemployment=pd.read_csv("Unemployment.csv", sep=",", on_bad_lines="skip")
population=pd.read_csv("Population.csv", sep=",", on_bad_lines="skip")
growth_gdp=pd.read_csv("GDP_growth.csv", sep=",", on_bad_lines="skip")
current_gdp.drop(current_gdp.columns[1:24], axis=1, inplace=True)
current_gdp.drop(current_gdp.columns[-1], axis=1, inplace=True)
print("\nThe inflation dataset/table looks like this :\n", current_gdp.head())
inflation.drop(inflation.columns[1:24], axis=1, inplace=True)
inflation.drop(inflation.columns[-1], axis=1, inplace=True)
print("\nThe inflation dataset/table looks like this :\n", inflation.head())
unemployment.drop(unemployment.columns[1:24], axis=1, inplace=True)
unemployment.drop(unemployment.columns[-1], axis=1, inplace=True)
print("\nThe inflation dataset/table looks like this :\n", unemployment.head())
population.drop(population.columns[1:24], axis=1, inplace=True)
population.drop(population.columns[-1], axis=1, inplace=True)
print("\nThe inflation dataset/table looks like this :\n", population.head())
growth_gdp.drop(growth_gdp.columns[1:24], axis=1, inplace=True)
growth_gdp.drop(growth_gdp.columns[-1], axis=1, inplace=True)
print("\nThe inflation dataset/table looks like this :\n", growth_gdp.head())
